name: Deploy to Azure SQL Database

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main

 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
    AZURE_DB_PROJECT_PATH: 'DEMOSQLDB'
    DOTNET_VERSION: '6.0'
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Build DACPAC file using Dotnet'
        shell: bash
        run: |
          cd ${{ env.AZURE_DB_PROJECT_PATH }}
          dotnet build /p:NetCoreBuild=true
    
      - name: Set up Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true 

      - name: Deploy DACPAC
        uses: azure/sql-action@v2
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: '${{ env.AZURE_DB_PROJECT_PATH }}/bin/debug/DEMOSQLDB.dacpac'
          action: 'Publish'
