name: Deploy to Azure SQL Database

on:
  push:
branches:
- main

jobs:
build-and-deploy:
runs-on: ubuntu-latest

steps:
- name: Checkout repository
uses: actions/checkout@v2

- name: Set up Azure Login
uses: azure/login@v1
with:
creds: ${{ secrets.AZURE_CREDENTIALS }}

- name: Create and Deploy DACPAC to Azure SQL Database
run: |
# Install DACPAC deployment tool
sudo apt-get update && sudo apt-get -y install dacpac

# Deploy DACPAC to Azure SQL Database
dacpac --TargetServerName=sqlldevops.database.windows.net \
--TargetDatabaseName=DemoDevOps \
--Username=DemoSql \
--Password=DemoDevOps$ \
--CreateNewDatabase=$(create_new_db) \
--Action=Publish \
--SourceFileC:\Users\pragysahoo\Documents\SQL\SQL\DEMOSQLDB\database.dacpac`.
```
