name: Deploy to Azure SQL Database

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main

 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install az cli
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Log in to Azure CLI
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      - name: Create and Deploy DACPAC to Azure SQL Database
        run: 
# Install DACPAC deployment tool
          sudo apt-get update && sudo apt-get -y install dacpac
      - name: Deploy DACPAC to Azure SQL Database
        run: 
# Deploy DACPAC to Azure SQL Database
          dacpac --TargetServerName=sqlldevops.database.windows.net \
          --TargetDatabaseName=DemoDevOps \
          --Username=DemoSql \
          --Password=DemoDevOps$ \
          --CreateNewDatabase=$(create_new_db) \
          --Action=Publish \
